### ISSUE TITLE
RevokeConsentDNTCommand

### ISSUE THREAD

**Issue by warquys** [Fondation-Azarus/SpecialSynapseStats#2]
make the command only "RevokeConsentDNTCommand" delete plugin data and not all data of the player.

**Comment by Bonjemus** [comment]
Why would you try to store data from a player who doesn't want you to do so and who also enabled DNT ?

**Comment by warquys** [comment]
I do not ask to store the data of a player who refuses consent. But, not to overdo the entire player database, only the keys related to this plugin.
